spring.datasource.url=jdbc:mysql://localhost:3306/todolist
spring.datasource.username=Vitax
spring.datasource.password=Vitor_1007
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update